### ISSUE TITLE
Asset compilation fails

### ISSUE THREAD

**Issue by kaji-bikash** [spirobel/projects#1] opened 2020-04-23 18:54 UTC
Trying to enable this plugin into the current version of Discourse fails with the following output.

```ruby
78954.470854151 Compressing: plugins/projects-fe2ea5a8cfbe65a7a4c2549cf8898efc05189a6ac16db43af79144ec69a9432a.js
uglifyjs '/var/www/discourse/public/assets/plugins/_projects-fe2ea5a8cfbe65a7a4c2549cf8898efc05189a6ac16db43af79144ec69a9432a.js' -m -c -o '/var/www/discourse/public/assets/plugins/projects-fe2ea5a8cfbe65a7a4c2549cf8898efc05189a6ac16db43af79144ec69a9432a.js' --source-map "base='/var/www/discourse/public/assets/plugins',root='/assets/plugins',url='/assets/plugins/projects-fe2ea5a8cfbe65a7a4c2549cf8898efc05189a6ac16db43af79144ec69a9432a.js.map'"
Parse error at _projects-fe2ea5a8cfbe65a7a4c2549cf8898efc05189a6ac16db43af79144ec69a9432a.js:104,21
      destroy: async function destroy(deleted_by) {
                     ^
ERROR: Unexpected token: keyword «function», expected: punc «,»
    at JS_Parse_Error.get (eval at <anonymous> (/usr/lib/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:71:23)
    at fatal (/usr/lib/node_modules/uglify-js/bin/uglifyjs:312:27)
    at run (/usr/lib/node_modules/uglify-js/bin/uglifyjs:255:9)
    at Object.<anonymous> (/usr/lib/node_modules/uglify-js/bin/uglifyjs:173:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.
```

**Comment by spirobel** [comment] 2020-04-24 03:18
Thank you very much for opening this issue. I will have a look at it!

**Comment by spirobel** [comment] 2020-05-02 10:02
Okay I can confirm the issue. seems like uglifyjs has a problem with async functions. 
```
84906.133613479 Compressing: plugins/projects-1b54332a8953eb5c2978afa2257c26d113ce0221637d99afa1694f1620de3f8f.js
uglifyjs '/var/www/discourse/public/assets/plugins/_projects-1b54332a8953eb5c2978afa2257c26d113ce0221637d99afa1694f1620de3f8f.js' -m -c -o '/var/www/discourse/public/assets/plugins/projects-1b54332a8953eb5c2978afa2257c26d113ce0221637d99afa1694f1620de3f8f.js' --source-map "base='/var/www/discourse/public/assets/plugins',root='/assets/plugins',url='/assets/plugins/projects-1b54332a8953eb5c2978afa2257c26d113ce0221637d99afa1694f1620de3f8f.js.map'"
Parse error at _projects-1b54384906.133613479 Compressing: plugins/projects-1b54332a8953eb5c2978afa2257c26d113ce0221637d99afa1694f1620de3f8f.js
uglifyjs '/var/www/discourse/public/assets/plugins/_projects-1b54332a8953eb5c2978afa2257c26d113ce0221637d99afa1694f1620de3f8f.js' -m -c -o '/var/www/discourse/public/assets/plugins/projects-1b54332a8953eb5c2978afa2257c26d113ce0221637d99afa1694f1620de3f8f.js' --source-map "base='/var/www/discourse/public/assets/plugins',root='/assets/plugins',url='/assets/plugins/projects-1b54332a8953eb5c2978afa2257c26d113ce0221637d99afa1694f1620de3f8f.js.map'"
Parse error at _projects-1b54332a8953eb5c2978afa2257c26d113ce0221637d99afa1694f1620de3f8f.js:108,32
      save_projects_task: async function save_projects_task() {
                                ^
ERROR: Unexpected token: keyword «function», expected: punc «,»
    at JS_Parse_Error.get (eval at <anonymous> (/usr/lib/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:71:23)
    at fatal (/usr/lib/node_modules/uglify-js/bin/uglifyjs:312:27)
    at run (/usr/lib/node_modules/uglify-js/bin/uglifyjs:255:9)
    at Object.<anonymous> (/usr/lib/node_modules/uglify-js/bin/uglifyjs:173:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
rake aborted!
32a8953eb5c2978afa2257c26d113ce0221637d99afa1694f1620de3f8f.js:108,32
      save_projects_task: async function save_projects_task() {
                                ^
ERROR: Unexpected token: keyword «function», expected: punc «,»
    at JS_Parse_Error.get (eval at <anonymous> (/usr/lib/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:71:23)
    at fatal (/usr/lib/node_modules/uglify-js/bin/uglifyjs:312:27)
    at run (/usr/lib/node_modules/uglify-js/bin/uglifyjs:255:9)
    at Object.<anonymous> (/usr/lib/node_modules/uglify-js/bin/uglifyjs:173:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
rake aborted!
```

**Comment by spirobel** [comment] 2020-05-02 10:12
It seems like I need to remove async/await from my code. I will close this issue when its done. https://meta.discourse.org/t/async-await-in-plugin-works-in-dev-instance-not-in-docker-instance/82363/14?u=spirobel

**Comment by spirobel** [comment] 2020-05-04 20:11
this seems to be working now. I installed it on my server. https://cidian.social/c/build-house/5 I want to use this plugin for my projects, so I will continue to improve it :D

**Closed as completed** 2020-05-04 20:11 UTC
